CREATE TABLE TRAINDETAILS(TrainNo INT PRIMARY KEY NOT NULL,TrainName VARCHAR(50) NOT NULL,FromStation VARCHAR(50) NOT NULL,ToStation VARCHAR(50) NOT NULL,
JourneyStartTime Time NOT NULL,JourneyEndTime Time NOT NULL)
SELECT * FROM TRAINDETAILS
DELETE FROM TRAINDETAILS

CREATE TABLE TRAINDAYS(Id INT PRIMARY KEY IDENTITY(101,1),SUNDAY bit NOT NULL,MONDAY bit NOT NULL,TUESDAY bit NOT NULL,WEDNESDAY bit NOT NULL
,THURSDAY bit NOT NULL,FRIDAY bit NOT NULL,SATURDAY bit NOT NULL, TrainNo INT,FOREIGN  KEY(Id) REFERENCES TRAINDETAILS(TrainNo))
SELECT * FROM TRAINDAYS
DROP TABLE TRAINDAYS


