CREATE TABLE TRAINDETAILS(TrainNo INT PRIMARY KEY NOT NULL,TrainName VARCHAR(50) NOT NULL,FromStation VARCHAR(50) NOT NULL,ToStation VARCHAR(50) NOT NULL,
JourneyStartTime Time NOT NULL,JourneyEndTime Time NOT NULL)

CREATE TABLE TRAINDAYS(TrainNo INT PRIMARY KEY,SUNDAY bit NOT NULL,MONDAY bit NOT NULL,TUESDAY bit NOT NULL,WEDNESDAY bit NOT NULL
,THURSDAY bit NOT NULL,FRIDAY bit NOT NULL,SATURDAY bit NOT NULL)
SELECT * FROM TRAINDETAILS
SELECT * FROM TRAINDAYS
DELETE FROM TRAINDETAILS
DELETE FROM TRAINDAYS

DROP TABLE TRAINDETAILS
DROP TABLE TRAINDAYS
